#include "audio/effects/distortion.h"
#include "audio/effect_factory.h"

namespace GuitarAmp {

static EffectRegistrar<Distortion> reg("Distortion");

Distortion::Distortion() {
    params_ = {
        {"Drive",  2.0f,  1.0f, 20.0f,  2.0f, "x", "Amount of input gain slamming into the hard clippers. Creates aggressive, dense harmonic distortion."},
        {"Tone",   0.6f,  0.0f,  1.0f,  0.6f, "", "Low-pass filter cutoff to tame the fizzy high-end generated by hard clipping."},
        {"Level",  0.5f,  0.0f,  1.0f,  0.5f, "", "Master output volume of the pedal. Useful to match volume with the pedal bypassed."},
    };
}

void Distortion::process(float* buffer, int num_samples) {
    if (!enabled_) return;

    float drive = params_[0].value;
    float tone = params_[1].value;
    float level = params_[2].value;

    // Tone control: simple one-pole LP filter coefficient
    float lp_coeff = 0.1f + tone * 0.8f;

    for (int i = 0; i < num_samples; ++i) {
        float dry = buffer[i];

        // Apply drive gain
        float x = buffer[i] * drive;

        // Hard clipping with asymmetric waveshaping
        x = fast_tanh(x);

        // Additional harmonic content via soft clip
        x = soft_clip(x * 1.5f);

        // Tone filter (one-pole LP)
        x = tone_lp_.lp(x, lp_coeff);

        // Output level
        x *= level;

        // Wet/dry mix
        buffer[i] = dry * (1.0f - mix_) + x * mix_;
    }
}

void Distortion::reset() {
    tone_lp_.reset();
}

} // namespace GuitarAmp
